### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by aliciabingham**

### CODE REVIEW

**Comment by aliciabingham** [comment]
i'm done. for the record.

**Comment by zoeames** [comment]
its mostly there but a few changes you must make. 
1.  you seem to be mixing bootstrap classes with hard coded pixel values - .activeClick class.  While this probably works on your machine my different screen size makes those two things not line up. So you should go back and get rid of the hard coded pixel values.  
2.  when i console out CarLot I only see 1 function - getInventory.  Check that you are Augmenting the original IIFE
3.  when I click on a car and start typing it should replace the description.  This does not seem to be working correctly.  Sometimes it just adds to the existing description and sometimes it does nothing.  Check your click events

**Comment by zoeames** [comment]
some things still need to be changed.  lets sit down and take a look at your code together after Gauntlet is done.

**Comment by zoeames** [comment]
your iifes look much better but i don't see the right functionality.  when i click on a car and start typing it only changes the LAST car.

**Comment by aliciabingham** [comment]
@zoeames

**Comment by zoeames** [comment]
There are some minor bugs with the colors BUT im ok with them 👍

**Comment by aliciabingham** [comment]
@zoeames good god, woman

**Pull request merged**
